export interface tblContacts {
    id?:number;
    rpyear?:string;
    pvcode?:string;
    pvname?:string;
    dentname?:string;
    mobile?:string;
    email?:string;
    job?:string;
    lineid?:string;
    khet?:string;
    pak?:string;
    isconfirm?:string;
    confirmdate?:string;
    birthyear?:string;
    postatus?:number;
    dateupdate?:string;
    posname?:string;
    posid?:string;
    stdel?:number;
    isconn?:string;
    denttype?:string;
    dentst?:string;
    numst?:string;
    sex?:string;
    d_update?:string;
    age?:number;
    yearbrth?:number
    }
    export interface tblProvince {
        id?:number;
        pvcode?:string;
        pvname?:string;
        ssjsize?:string;
        password?:string;
        tel?:number;
        khet?:string;
        pak?:string;
        dentistnum?:number;
        tuntanum?:number;
        assistnum?:number;
        vichakannum?:number;
        isconfirm?:string;
        confirmdate?:string;
        dateupdate?:string;
        isclinic?:number;
        cont_update?:number;
        others?:string;
        iscommitee?:string;
        email?:string;
        address?:string;
        contactname?:string;
        contacttel?:string;
        }